### ISSUE TITLE
Ordering decks on the website by Need does not result in a proper order

### ISSUE THREAD

**Issue by bbrala** [Razviar/mtga-pro-tracker#165]
**Describe the bug**
Ordering decks on the website by Need does not result in a proper order. Seems the logic might be off?

**To Reproduce**
1. Go to 'decks'
2. Click on 'Need column'

**Expected behavior**
Would assume it orders by how many wildcards you need.

**Comment by Razviar** [comment]
Issue is being fixed now

**Comment by bbrala** [comment]
But not deployed yet? I still get the same ordering results :)

**Comment by bbrala** [comment]
Ik misread, missed the word 'being' sorry +1

Sent from Nine<http://www.9folders.com/>
________________________________
Van: Razviar <notifications@github.com>
verzonden: woensdag 14 november 2018 20:09
Aan: Razviar/mtga-pro-tracker
Cc: Björn Brala; Author
Onderwerp: Re: [Razviar/mtga-pro-tracker] Ordering decks on the website by Need does not result in a proper order (#165)


I didn't close the issue, so it is not solved yet. We are still working on it.
