### ISSUE TITLE
Incorrect W/L ratio

### ISSUE THREAD

**Issue by Sztokholm** [Razviar/mtga-pro-tracker#331]
My W/L ratio on MTGA Pro app and webpage is incorrect. Since account wipe all my matches are registered as losses (0/23). Altough I was playing whole weekend with around 60-70% win ratio.

Please find the screenshot in the attachment.

Hope it helps and that I am not the only one with that issue! It's pretty inconvenient :)

Sztokholm
![img_0856](https://user-images.githubusercontent.com/47717338/52914717-1b0c0300-32cc-11e9-9a98-10f810944b56.jpg)

**Comment by Razviar** [comment]
Issue causing wrong w/l is fixed.

**Comment by Sztokholm** [comment]
I still see 0% W/L ratio. Will the past ratio be visible? If not could you wipe up my stats please?

**Comment by Razviar** [comment]
All I can advice is self-remove you account using "Delete Account" tool in Edit Profile section and register again with empty stats. We don't do manual editing of user data since it's very time consuming and inefficient.

**Comment by Sztokholm** [comment]
Will do, thanks bro!
